### ISSUE TITLE
Win32 binary

### ISSUE THREAD

**Issue by jnus** [taurus-forever/diffpdf-console#1]
Anyone by change have win32 binaries laying around, they could upload/send? I'll put it on chocolatey.org if anyone can provide me with binaries ;)

Thanks J.

**Comment by taurus-forever** [comment]
Hi!

If you are looking original diffpdf Windows binaries, you can find them here:
http://www.qtrac.eu/diffpdf.html note latest version is 5.3.1 
Direct link is:  http://www.qtrac.eu/DiffPDF-5.3.1-win32.msi 

While diffpdf-console has been forked from version 2.1.2 (also you can find old diffpdf 2.1.2 here: https://web.archive.org/web/20130530051111/http://www.qtrac.eu/diffpdf-2.1.2-win32-static.zip )

You can find build instruction in Internet archive:
https://web.archive.org/web/20130530051111/http://www.qtrac.eu/diffpdf.html

```
 To build DiffPDF you will need a good C++ compiler (e.g., GCC), the Qt 4 libraries 
(at least Qt 4.4; 4.6 or later recommended), and the Poppler library (at least 0.20.1)
all these should be available as standard packages on most Linux and BSD systems. 
Building follows the standard pattern for Qt 4 applications and is explained in the README;
the steps are reproduced here:

    tar xvfz diffpdf-XXX.tar.gz # Unpack the archive file, diffpdf-XXX.tar.gz
    cd diffpdf-XXX # Change to the source directory
    lrelease diffpdf.pro # On some systems, run lrelease-qt4
    qmake # On some systems, run qmake-qt4
    make # Build the program
```

It should work for diffpdf-console fine. Unfortunately I do not use Windows to build it for you.
